### ISSUE TITLE
Question about the kernel size

### ISSUE THREAD

**Issue by KnightWin123** [wanggrun/Adaptively-Connected-Neural-Networks#5]
Hi! Thank you for sharing your code.May be the question is stupid, but I hope you can answer it for me.Why don't you replace conv2d with grconv when kernel size equl to 1

**Comment by baoyucumt** [comment]
this is not confirmed that the filter size is 1, you can change it. but for 1dcnn, one dimension should be 1.

**Comment by KnightWin123** [comment]
thanks
